services:

  worker-ai-summary:
    image: linklian-inference:latest
    command: ["--queue", "ai_summary_queue"]
    environment:
      REDIS_HOST: linklian-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      QDRANT_STORE: ${QDRANT_STORE}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    networks:
      - linklian-net
    deploy:
      restart_policy:
        condition: any

  worker-qdrant-vector-store:
    image: linklian-inference:latest
    command: ["--queue", "qdrant_vector_store"]
    environment:
      REDIS_HOST: linklian-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      QDRANT_STORE: ${QDRANT_STORE}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    networks:
      - linklian-net
    deploy:
      restart_policy:
        condition: any

  worker-quiz-generation:
    image: linklian-inference:latest
    command: ["--queue", "quiz_generation_queue"]
    environment:
      REDIS_HOST: linklian-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      QDRANT_STORE: ${QDRANT_STORE}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    networks:
      - linklian-net
    deploy:
      restart_policy:
        condition: any

  worker-qa-chat:
    image: linklian-inference:latest
    command: ["--queue", "qa_chat_queue"]
    environment:
      REDIS_HOST: linklian-redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      QDRANT_STORE: ${QDRANT_STORE}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION: ${QDRANT_COLLECTION}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    networks:
      - linklian-net
    deploy:
      restart_policy:
        condition: any

networks:
  linklian-net:
    driver: overlay
    attachable: true
